# This workflow is used to convert the version in the `VERSION` file into a valid `git tag` on push to `main`.
# We use the `VERSION` file to denote the version of the config once a PR is merged.
name: Bump Tag
on:
  push:
    branches:
      - 'release-*'
    paths:
      - 'VERSION'
jobs:
  tag-update:
    name: Check and Update Tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Existing Tag Check
        # Check if the tag already exists, if it does, we don't want to move it.
        id: tag
        run: |
          VERSION_TAG=$(git tag -l $(cat VERSION))
          if [ -n "$VERSION_TAG" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "::warning::Tag $VERSION_TAG already exists. Skipping."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Update Tag
        if: steps.tag.outputs.exists == 'false'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag $(cat VERSION)
          git push --tags
