name: Scheduled Checks - Branch Specific
on:
  workflow_call:
    inputs:
      config-tag:
        type: string
        required: true
        description: Tag associated with a config branch that is used in the reproducibility run
jobs:
  repro-ci:
    uses: access-nri/reproducibility/.github/workflows/checks.yml@main
    with:
      model-name: access-om2
      config-tag: ${{ inputs.config-tag }}
    secrets: inherit
    permissions:
      contents: write

  check-repro:
    name: Check Repro Results
    needs:
      - repro-ci
    runs-on: ubuntu-latest
    env:
      CHECKSUM_LOCAL_LOCATION: /opt/checksums
    outputs:
      result: ${{ steps.check.outputs.result }}
      ground-truth-version: ${{ steps.check.outputs.ground-truth-version }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ needs.repro-ci.outputs.artifact-name }}
          path: ${{ env.CHECKSUM_LOCAL_LOCATION }}

      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.config-tag }}

      - name: Check Repro
        id: check
        uses: access-nri/reproducibility/.github/actions/checksum-check@main
        with:
          checksum-location: ${{ env.CHECKSUM_LOCAL_LOCATION }}

  failed-repro:
    name: Failed Reproduction
    needs:
      - check-repro
    if: needs.check-repro.outputs.result == 'false'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # something more drastic
