name: Scheduled Checks - Branch Specific
on:
  workflow_call:
    inputs:
      config-branch:
        type: string
        required: true
        description: A config branch to use for the reproducibility run
jobs:
  repro-ci:
    uses: ./.github/workflows/repro-ci.yml
    with:
      model-name: access-om2
      config-branch: ${{ inputs.config-branch }}

  successful-repro:
    name: Successful Reproduction
    needs:
      - repro-ci
    if: needs.repro.outputs.result == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  failed-repro:
    name: Failed Reproduction
    needs:
      - repro-ci
    if: needs.repro.outputs.result == 'false'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
