name: Scheduled Checks - Branch Specific
on:
  workflow_call:
    inputs:
      config-branch:
        type: string
        required: true
        description: A config branch to use for the reproducibility run
jobs:
  repro-ci:
    uses: ./.github/workflows/repro-ci.yml
    with:
      model-name: access-om2
      config-branch: ${{ inputs.config-branch }}

  check-repro:
    name: Check Repro Results
    needs:
      - repro-ci
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.check.outputs.result }}
      ground-truth-version: ${{ steps.check.outputs.ground-truth-version }}
    steps:
      - name: Download and check repro results, similar to pr-1-ci.yml
        run: # do the above

  successful-repro:
    name: Successful Reproduction
    needs:
      - check-repro
    if: needs.check-repro.outputs.result == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  failed-repro:
    name: Failed Reproduction
    needs:
      - repro-ci
    if: needs.check-repro.outputs.result == 'false'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
