name: Scheduled Checks - Branch Specific
on:
  workflow_call:
    inputs:
      config-tag:
        type: string
        required: true
        description: Tag associated with a config branch that is used in the reproducibility run
jobs:
  repro-ci:
    uses: ./.github/workflows/repro-ci.yml
    with:
      model-name: access-om2
      config-tag: ${{ inputs.config-tag }}

  check-repro:
    name: Check Repro Results
    needs:
      - repro-ci
    uses: ./.github/workflows/check-repro.yml
    with:
      artifact-name: ${{ needs.repro-ci.outputs.artifact-name }}
      config-tag: ${{ inputs.config-tag }}

  successful-repro:
    name: Successful Reproduction
    needs:
      - check-repro
    if: needs.check-repro.outputs.result == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  failed-repro:
    name: Failed Reproduction
    needs:
      - check-repro
    if: needs.check-repro.outputs.result == 'false'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # something more drastic
